# Generated by Django 3.2 on 2021-10-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmworkgenre',
            unique_together={('film_work', 'genre')},
        ),
    ]
